# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cc80b1045431748e1d6653ba9e515af756d43a762480f9d585e824f40ae882060dd1b2b018d738e0525f5bc52aa51d4814149b92c3e5b817e884f50598540d6b

test:
  secret_key_base: 6571950092e10ff4548f5f2326ed34a39d8ee8e03e2ed1a1a1edae7824a1ee38cb001356eaafa34871dbf7c76ffc1397709ba86a96542173cc55192f6bd7a408

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
